name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/jmeter-graphql-api.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO -JapiKey=${{ secrets.X_API_KEY }} -Jauth=\"${{ secrets.AUTH }}\" -JtestFileName=tests/story-query.graphql -Jprotocol=https -Jhost=origin.qa2-news.lower.ap.brightspot.cloud"

      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: reports/
          retention-days: 1

